const languageData = [
    { code: 'cmn', name: 'Mandarin Chinese' },
    { code: 'spa', name: 'Spanish' },
    { code: 'eng', name: 'English' },
    { code: 'rus', name: 'Russian' },
    { code: 'arb', name: 'Standard Arabic' },
    { code: 'ben', name: 'Bengali' },
    { code: 'hin', name: 'Hindi' },
    { code: 'por', name: 'Portuguese' },
    { code: 'ind', name: 'Indonesian' },
    { code: 'jpn', name: 'Japanese' },
    { code: 'fra', name: 'French' },
    { code: 'deu', name: 'German' },
    { code: 'jav', name: 'Javanese (Javanese)' },
    { code: 'kor', name: 'Korean' },
    { code: 'tel', name: 'Telugu' },
    { code: 'vie', name: 'Vietnamese' },
    { code: 'mar', name: 'Marathi' },
    { code: 'ita', name: 'Italian' },
    { code: 'tam', name: 'Tamil' },
    { code: 'tur', name: 'Turkish' },
    { code: 'urd', name: 'Urdu' },
    { code: 'guj', name: 'Gujarati' },
    { code: 'pol', name: 'Polish' },
    { code: 'ukr', name: 'Ukrainian' },
    { code: 'kan', name: 'Kannada' },
    { code: 'mai', name: 'Maithili' },
    { code: 'mal', name: 'Malayalam' },
    { code: 'pes', name: 'Iranian Persian' },
    { code: 'mya', name: 'Burmese' },
    { code: 'swh', name: 'Swahili (individual language)' },
    { code: 'sun', name: 'Sundanese' },
    { code: 'ron', name: 'Romanian' },
    { code: 'pan', name: 'Panjabi' },
    { code: 'bho', name: 'Bhojpuri' },
    { code: 'amh', name: 'Amharic' },
    { code: 'hau', name: 'Hausa' },
    { code: 'fuv', name: 'Nigerian Fulfulde' },
    { code: 'bos', name: 'Bosnian (Cyrillic)' },
    { code: 'hrv', name: 'Croatian' },
    { code: 'nld', name: 'Dutch' },
    { code: 'srp', name: 'Serbian' },
    { code: 'tha', name: 'Thai' },
    { code: 'ckb', name: 'Central Kurdish' },
    { code: 'yor', name: 'Yoruba' },
    { code: 'uzn', name: 'Northern Uzbek' },
    { code: 'zlm', name: 'Malay' },
    { code: 'ibo', name: 'Igbo' },
    { code: 'npi', name: 'Nepali' },
    { code: 'ceb', name: 'Cebuano' },
    { code: 'skr', name: 'Saraiki' },
    { code: 'tgl', name: 'Tagalog' },
    { code: 'hun', name: 'Hungarian' },
    { code: 'azj', name: 'North Azerbaijani' },
    { code: 'sin', name: 'Sinhala' },
    { code: 'koi', name: 'Komi-Permyak' },
    { code: 'ell', name: 'Modern Greek' },
    { code: 'ces', name: 'Czech' },
    { code: 'mag', name: 'Magahi' },
    { code: 'run', name: 'Rundi' },
    { code: 'bel', name: 'Belarusian' },
    { code: 'plt', name: 'Plateau Malagasy' },
    { code: 'qug', name: 'Chimborazo Highland Quichua' },
    { code: 'mad', name: 'Madurese' },
    { code: 'nya', name: 'Nyanja' },
    { code: 'zyb', name: 'Yongbei Zhuang' },
    { code: 'pbu', name: 'Northern Pashto' },
    { code: 'kin', name: 'Kinyarwanda' },
    { code: 'zul', name: 'Zulu' },
    { code: 'bul', name: 'Bulgarian' },
    { code: 'swe', name: 'Swedish' },
    { code: 'lin', name: 'Lingala' },
    { code: 'som', name: 'Somali' },
    { code: 'hms', name: 'Southern Qiandong Miao' },
    { code: 'hnj', name: 'Hmong Njua' },
    { code: 'ilo', name: 'Iloko' },
    { code: 'kaz', name: 'Kazakh' },
    { code: 'uig', name: 'Uighur' },
    { code: 'hat', name: 'Haitian' },
    { code: 'khm', name: 'Khmer' },
    { code: 'prs', name: 'Dari' },
    { code: 'hil', name: 'Hiligaynon' },
    { code: 'sna', name: 'Shona' },
    { code: 'tat', name: 'Tatar' },
    { code: 'xho', name: 'Xhosa' },
    { code: 'hye', name: 'Armenian' },
    { code: 'min', name: 'Minangkabau' },
    { code: 'afr', name: 'Afrikaans' },
    { code: 'lua', name: 'Luba-Lulua' },
    { code: 'sat', name: 'Santali' },
    { code: 'bod', name: 'Tibetan' },
    { code: 'tir', name: 'Tigrinya' },
    { code: 'fin', name: 'Finnish' },
    { code: 'slk', name: 'Slovak' },
    { code: 'tuk', name: 'Turkmen' },
    { code: 'dan', name: 'Danish' },
    { code: 'nob', name: 'Norwegian Bokmål' },
    { code: 'suk', name: 'Sukuma' },
    { code: 'als', name: 'Tosk Albanian' },
    { code: 'sag', name: 'Sango' },
    { code: 'nno', name: 'Norwegian Nynorsk' },
    { code: 'heb', name: 'Hebrew' },
    { code: 'mos', name: 'Mossi' },
    { code: 'tgk', name: 'Tajik' },
    { code: 'cat', name: 'Catalan' },
    { code: 'sot', name: 'Southern Sotho' },
    { code: 'kat', name: 'Georgian' },
    { code: 'bcl', name: 'Central Bikol' },
    { code: 'glg', name: 'Galician' },
    { code: 'lao', name: 'Lao' },
    { code: 'lit', name: 'Lithuanian' },
    { code: 'umb', name: 'Umbundu' },
    { code: 'tsn', name: 'Tswana' },
    { code: 'vec', name: 'Venetian' },
    { code: 'nso', name: 'Pedi' },
    { code: 'ban', name: 'Balinese' },
    { code: 'bug', name: 'Buginese' },
    { code: 'knc', name: 'Central Kanuri' },
    { code: 'kng', name: 'Koongo' },
    { code: 'ibb', name: 'Ibibio' },
    { code: 'lug', name: 'Ganda' },
    { code: 'ace', name: 'Achinese' },
    { code: 'bam', name: 'Bambara' },
    { code: 'tzm', name: 'Central Atlas Tamazight' },
    { code: 'ydd', name: 'Eastern Yiddish' },
    { code: 'kmb', name: 'Kimbundu' },
    { code: 'lun', name: 'Lunda' },
    { code: 'shn', name: 'Shan' },
    { code: 'war', name: 'Waray (Philippines)' },
    { code: 'dyu', name: 'Dyula' },
    { code: 'wol', name: 'Wolof' },
    { code: 'kir', name: 'Kirghiz' },
    { code: 'nds', name: 'Low German' },
    { code: 'fuf', name: 'Pular' },
    { code: 'mkd', name: 'Macedonian' },
    { code: 'vmw', name: 'Makhuwa' },
    { code: 'zgh', name: 'Standard Moroccan Tamazight' },
    { code: 'ewe', name: 'Ewe' },
    { code: 'khk', name: 'Halh Mongolian' },
    { code: 'slv', name: 'Slovenian' },
    { code: 'ayr', name: 'Central Aymara' },
    { code: 'bem', name: 'Bemba (Zambia)' },
    { code: 'emk', name: 'Eastern Maninkakan' },
    { code: 'bci', name: 'Baoulé' },
    { code: 'bum', name: 'Bulu (Cameroon)' },
    { code: 'epo', name: 'Esperanto' },
    { code: 'pam', name: 'Pampanga' },
    { code: 'tiv', name: 'Tiv' },
    { code: 'tpi', name: 'Tok Pisin' },
    { code: 'ven', name: 'Venda' },
    { code: 'ssw', name: 'Swati' },
    { code: 'nyn', name: 'Nyankole' },
    { code: 'kbd', name: 'Kabardian' },
    { code: 'iii', name: 'Sichuan Yi' },
    { code: 'yao', name: 'Yao' },
    { code: 'lvs', name: 'Standard Latvian' },
    { code: 'quz', name: 'Cusco Quechua' },
    { code: 'src', name: 'Logudorese Sardinian' },
    { code: 'rup', name: 'Macedo-Romanian' },
    { code: 'sco', name: 'Scots' },
    { code: 'tso', name: 'Tsonga' },
    { code: 'men', name: 'Mende (Sierra Leone)' },
    { code: 'fon', name: 'Fon' },
    { code: 'nhn', name: 'Central Nahuatl' },
    { code: 'dip', name: 'Northeastern Dinka' },
    { code: 'kde', name: 'Makonde' },
    { code: 'kbp', name: 'Kabiyè' },
    { code: 'tem', name: 'Timne' },
    { code: 'toi', name: 'Tonga (Zambia)' },
    { code: 'ekk', name: 'Standard Estonian' },
    { code: 'snk', name: 'Soninke' },
    { code: 'cjk', name: 'Chokwe' },
    { code: 'ada', name: 'Adangme' },
    { code: 'aii', name: 'Assyrian Neo-Aramaic' },
    { code: 'quy', name: 'Ayacucho Quechua' },
    { code: 'rmn', name: 'Balkan Romani' },
    { code: 'bin', name: 'Bini' },
    { code: 'gaa', name: 'Ga' },
    { code: 'ndo', name: 'Ndonga' },
  ];

  export default languageData;